#Requires -Version 5.1
# Example .jst/bootstrap.ps1 — the optional per-worktree bootstrap hook (Windows).
#
# THIS IS AN EXAMPLE, NOT A TEMPLATE TO FILL IN. Copy it to .jst/bootstrap.ps1 in
# your own project and rewrite it for your stack — nothing here is parsed, and
# there is no required structure. It mirrors bootstrap.example.sh step for step,
# which is the shape to keep if your team spans both OSes: same env-var contract,
# same instance derivation, so a worktree gets the same ports either way.
#
# WHAT RUNS THIS: jira-task-executor, in its step 1, once per worktree, at the
# moment someone is about to work in it — automatically, with no confirmation
# prompt. Why the executor and not the assigner: a multistep assigner run
# creates N worktrees in one unattended pass and would stand up N running
# environments at once.
#
# FAIL-SOFT: a non-zero exit is reported in the executor's output and the run
# continues. You cannot block the executor from here, so don't try — exit
# non-zero to say "this worktree isn't runnable yet", not "stop working".
#
# IDEMPOTENCY IS YOUR JOB: a re-run of the executor in the same worktree
# re-invokes this script. Every step below is create-if-missing or reuse.
#
# Full contract: skills/_shared/project-config.md § the optional worktree hook.
# Share-vs-isolate reasoning behind these decisions: docs/RUNNING-MULTIPLE-COPIES.md.

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# -----------------------------------------------------------------------------
# The environment contract. The executor sets all five; defaults here keep the
# script runnable by hand, which is how you'll debug it.
# -----------------------------------------------------------------------------
$Branch = if ($env:JST_BRANCH) { $env:JST_BRANCH } else { (& git branch --show-current).Trim() }
$IssueKey = if ($env:JST_ISSUE_KEY) {
    $env:JST_ISSUE_KEY
} elseif ($Branch -match '^[^/]+/([A-Z][A-Z0-9]+-[0-9]+)') {
    $Matches[1]
} else {
    ''
}
$WorktreeDir = if ($env:JST_WORKTREE_DIR) { $env:JST_WORKTREE_DIR } else { (& git rev-parse --show-toplevel).Trim() }
$ParentBranch = if ($env:JST_PARENT_BRANCH) { $env:JST_PARENT_BRANCH } else { '' }   # empty when unset — not an error
$ProjectKey = if ($env:JST_PROJECT_KEY) { $env:JST_PROJECT_KEY } else { 'PROJ' }

Set-Location -LiteralPath $WorktreeDir

# -----------------------------------------------------------------------------
# The instance index. DERIVE IT DETERMINISTICALLY FROM THE ISSUE KEY — that is
# what makes the ports stable across re-runs and non-colliding across worktrees.
# Never allocate "the next free index": two worktrees bootstrapping at once
# would race, and the same worktree would drift between runs.
#
# Index 0 belongs to the main checkout's own stack, so map into 1..63 and leave
# it alone. Modulo means two issue numbers 64 apart collide; that is a real
# (rare) failure and the message below says so instead of corrupting a stack.
#
# [int] rounds half-to-even in PowerShell where other languages truncate, so
# parse the numeric part explicitly rather than casting a computed value.
# -----------------------------------------------------------------------------
$IssueNum = [int]($IssueKey -replace '^.*-', '')
$Instance = ($IssueNum % 63) + 1

$DbPort = 55432 + $Instance
$AppPort = 8000 + $Instance
$ComposeProject = "$($ProjectKey.ToLowerInvariant())-i$Instance"
$StateDir = Join-Path $WorktreeDir ".instances\$Instance"

Write-Host "bootstrap: $IssueKey on $Branch (parent: $(if ($ParentBranch) { $ParentBranch } else { 'none' }))"
Write-Host "bootstrap: instance $Instance — db :$DbPort, app :$AppPort, compose $ComposeProject"

# -----------------------------------------------------------------------------
# 1. Per-instance state directory + rendered config. Idempotent: -Force on the
#    directory, and the env file is rewritten from scratch each run so a changed
#    port scheme actually takes effect.
# -----------------------------------------------------------------------------
New-Item -ItemType Directory -Force -Path (Join-Path $StateDir 'pgdata'), (Join-Path $StateDir 'uploads') | Out-Null

@"
# Generated by .jst/bootstrap.ps1 for $IssueKey — do not edit by hand.
DB_HOST=localhost
DB_PORT=$DbPort
DB_NAME=myapp
MEDIA_ROOT=$(Join-Path $StateDir 'uploads')
DEV_SERVER_PORT=$AppPort
"@ | Set-Content -LiteralPath (Join-Path $WorktreeDir '.env.local') -Encoding UTF8

# Secrets are NOT re-derived — copy them from the main checkout, which stays
# their single source of truth. `git worktree list` finds it without guessing.
$MainCheckout = (& git worktree list --porcelain |
    Where-Object { $_ -match '^worktree (.+)$' } |
    ForEach-Object { $Matches[1] } | Select-Object -First 1)
$secrets = Join-Path $MainCheckout '.env.secrets'
if (Test-Path -LiteralPath $secrets -PathType Leaf) {
    Copy-Item -LiteralPath $secrets -Destination (Join-Path $WorktreeDir '.env.secrets') -Force
}

# -----------------------------------------------------------------------------
# 2. Dependencies. Each worktree has its own virtualenv. Cheap to skip when
#    already satisfied, so check before spending the time.
# -----------------------------------------------------------------------------
$venv = Join-Path $WorktreeDir '.venv'
if (-not (Test-Path -LiteralPath $venv -PathType Container)) {
    & python -m venv $venv
}
& (Join-Path $venv 'Scripts\pip.exe') install -q -r requirements.txt

# -----------------------------------------------------------------------------
# 3. This instance's database container. `up -d` is already idempotent — it
#    reuses a running container rather than erroring — which is why this is
#    plain `up` and not a stop/rm/create dance.
# -----------------------------------------------------------------------------
$env:DB_PORT = "$DbPort"
$env:PGDATA_DIR = (Join-Path $StateDir 'pgdata')
& docker compose -p $ComposeProject -f docker-compose.worktree.yml up -d

# Wait for it rather than racing the migration below.
foreach ($i in 1..30) {
    & pg_isready -h localhost -p $DbPort -q
    if ($LASTEXITCODE -eq 0) { break }
    Start-Sleep -Seconds 1
}

# -----------------------------------------------------------------------------
# 4. Seed the database — only when it's empty. This is the step that most needs
#    the idempotency guard: re-running the executor must not wipe work already
#    done in this worktree.
# -----------------------------------------------------------------------------
$seeded = Join-Path $StateDir '.seeded'
if (-not (Test-Path -LiteralPath $seeded -PathType Leaf)) {
    $dump = Join-Path $MainCheckout 'appdb.sql'
    if (Test-Path -LiteralPath $dump -PathType Leaf) {
        & psql -h localhost -p $DbPort -U myapp -d myapp -q -f $dump
        New-Item -ItemType File -Path $seeded | Out-Null
    } else {
        # Non-zero: this worktree isn't fully runnable, and the executor will
        # say so and carry on. Tell the human exactly how to finish the job.
        Write-Error "bootstrap: no baseline dump at $dump — the database is empty."
        Write-Host "bootstrap: produce one with 'pg_dump -U myapp -d myapp > appdb.sql' from the main checkout, then re-run."
        exit 1
    }
}

& (Join-Path $venv 'Scripts\python.exe') manage.py migrate --noinput

Write-Host "bootstrap: ready — start the app with '.venv\Scripts\python.exe manage.py runserver 0.0.0.0:$AppPort'"

# -----------------------------------------------------------------------------
# IF YOUR PROJECT IS STATELESS, THIS FILE IS MUCH SHORTER.
# A frontend or stateless service has no external state to duplicate, only a
# port to move. The whole hook can legitimately be:
#
#   Set-StrictMode -Version Latest
#   $ErrorActionPreference = 'Stop'
#   Set-Location -LiteralPath $env:JST_WORKTREE_DIR
#   & npm install --silent
#   $port = 5174 + ([int]($env:JST_ISSUE_KEY -replace '^.*-','') % 100)
#   "PORT=$port" | Set-Content .env.local -Encoding UTF8
#   Write-Host "bootstrap: run 'npm run dev' — it will serve on :$port"
#
# Write the shorter version rather than padding it out to look like the one
# above. The hook earns its place by doing what someone would otherwise have to
# work out by hand — not by covering every step in this example.
# -----------------------------------------------------------------------------
