# feature_report.ps1 [<json-path>]
#
# Report-builder half of the feature roll-up: consumes the collect_feature JSON
# and renders a markdown feature report from it. The pipeline is
#   collect_feature.ps1 <KEY>  ->  JSON  ->  feature_report.ps1  ->  markdown
# collect_feature is the single OWNER of the JSON schema
# (see references/feature-report-schema.md); this script only READS it and never
# re-measures — every number rendered here is a value the collector already
# emitted.
#
# Input — a path and/or stdin (whichever is given):
#   feature_report.ps1 report.json > report.md      # from a file
#   collect_feature.ps1 JST-93 | feature_report.ps1 > report.md   # from stdin
# A '-' path also means stdin. With no path and no piped input it prints usage
# and exits 1 rather than blocking on the console.
#
# Output: the markdown report on stdout, nothing else. Read-only: it neither
# writes files nor touches Jira/git.
#
# Windows (PowerShell 5.1+) only this round; the posix twin
# (../posix/feature_report.sh) is a STUB that exits non-zero — a deliberate,
# explicit parity gap, not a silent one.
#
# Exit: 0 = markdown emitted   1 = usage / unreadable-or-invalid JSON

$ErrorActionPreference = 'Stop'
function Fail([string]$msg) { [Console]::Error.WriteLine("feature_report: $msg"); exit 1 }

# ---- read the JSON (path arg, or stdin) -------------------------------------
$PipedInput = @($input)   # capture the PS object pipeline before it's consumed
$PathArg = if ($args.Count -ge 1) { [string]$args[0] } else { '' }
$raw = $null
if ($PathArg -and $PathArg -ne '-') {
    if (-not (Test-Path -LiteralPath $PathArg -PathType Leaf)) { Fail "no such JSON file: $PathArg" }
    $raw = [System.IO.File]::ReadAllText($PathArg)
} elseif ($PipedInput.Count -gt 0) {
    # Invoked as a stage in a PowerShell pipeline (… | .\feature_report.ps1): the
    # JSON arrives as objects on the PS object pipeline, not the process's console
    # stdin, so [Console]::In is empty here. -join (not Out-String) rebuilds the
    # text without width-wrapping long JSON lines.
    $raw = ($PipedInput -join "`n")
} elseif ($PathArg -eq '-' -or [Console]::IsInputRedirected) {
    # Entry point of its own process with redirected stdin: pwsh -File … piped
    # from another process, or an explicit '-' path.
    $raw = [Console]::In.ReadToEnd()
} else {
    Fail 'need collect_feature JSON: pass a path, or pipe it in (collect_feature.ps1 <KEY> | feature_report.ps1).'
}
if ([string]::IsNullOrWhiteSpace($raw)) { Fail 'empty input -- no JSON to render.' }

try { $data = $raw | ConvertFrom-Json -ErrorAction Stop } catch { Fail 'input is not valid JSON (expected collect_feature output).' }
if ($null -eq $data.feature -or $null -eq $data.conversations -or $null -eq $data.aggregate) {
    Fail 'JSON is missing feature/conversations/aggregate -- is this collect_feature output?'
}

# ---- formatting helpers -----------------------------------------------------
# Only $null / '' render as '-'; a measured 0 must render as 0. (Guard against
# PowerShell coercing '' to numeric 0 in `-eq`, which would hide real zeros.)
function Num([object]$n)  { if ($null -eq $n -or ($n -is [string] -and $n -eq '')) { return '-' }; return ('{0:N0}' -f [long]$n) }
function Sec([object]$n)  { if ($null -eq $n -or ($n -is [string] -and $n -eq '')) { return '-' }; return ('{0:N1}' -f [double]$n) }
function Join-List($xs)   { if ($null -eq $xs) { return '-' }; $a = @($xs); if ($a.Count -eq 0) { return '-' }; return ($a -join ', ') }
# Timestamps arrive as DateTime (ConvertFrom-Json auto-parses the ISO-Z strings)
# or, on older hosts, as the raw string — render either as compact UTC.
function Ts([object]$v)  {
    if ($null -eq $v -or $v -eq '') { return '-' }
    if ($v -is [datetime])       { return $v.ToUniversalTime().ToString("yyyy-MM-dd HH:mm:ss'Z'") }
    if ($v -is [datetimeoffset]) { return $v.UtcDateTime.ToString("yyyy-MM-dd HH:mm:ss'Z'") }
    return [string]$v
}
# Seconds -> human span (collector-provided number, formatted only — not computed here).
function Dur([object]$sec) {
    if ($null -eq $sec -or $sec -eq '') { return '-' }
    $t = [timespan]::FromSeconds([double]$sec)
    if ($t.TotalHours   -ge 1) { return ('{0}h {1}m {2}s' -f [int]$t.TotalHours, $t.Minutes, $t.Seconds) }
    if ($t.TotalMinutes -ge 1) { return ('{0}m {1}s' -f [int]$t.TotalMinutes, $t.Seconds) }
    return ('{0:N1}s' -f [double]$sec)
}
$nl = "`n"
$out = New-Object System.Collections.Generic.List[string]
function W([string]$s) { $out.Add($s) }

$agg = $data.aggregate
$conv = @($data.conversations)

# ---- header + summary -------------------------------------------------------
W "# Feature report — $($data.feature)"
W ''
$analyzed = if ($null -ne $agg.analyzed_count) { $agg.analyzed_count } else { $conv.Count }
W "_Generated by ``feature_report`` from ``collect_feature`` JSON — $($conv.Count) conversation(s), $analyzed with measured metrics. Every figure is the collector's own; nothing is re-estimated._"
W ''
W '## Summary'
W ''
W '| metric | value |'
W '|---|---|'
W "| Feature | $($data.feature) |"
W "| Conversations | $($conv.Count) (analyzed: $analyzed) |"
W "| **Total token consumption** | **$(Num $agg.tokens.total)** |"
W "| — input | $(Num $agg.tokens.in) |"
W "| — output | $(Num $agg.tokens.out) |"
W "| — cache read | $(Num $agg.tokens.cache_read) |"
W "| — cache write | $(Num $agg.tokens.cache_write) |"
W "| Models used | $(Join-List $agg.models) |"
W "| Skills exercised | $(Join-List $agg.skills) |"
W "| Issue keys touched | $(Join-List $agg.issue_keys) |"
if ($null -ne $agg.skill_turns)  { W "| Total skill turns | $(Num $agg.skill_turns) |" }
if ($null -ne $agg.tool_calls)   { W "| Total tool calls | $(Num $agg.tool_calls) (errors: $(Num $agg.tool_errors)) |" }
if ($agg.timeframe -and $null -ne $agg.timeframe.span_s) {
    W "| Activity span | $(Dur $agg.timeframe.span_s) ($(Ts $agg.timeframe.first_ts) → $(Ts $agg.timeframe.last_ts)) |"
}
W ''

# ---- per-conversation tokens table ------------------------------------------
W '## Per-conversation — tokens'
W ''
W '| conversation | provenance | skill | issue | model(s) | in | out | cache-read | cache-write | total | tool calls | elapsed (s) |'
W '|---|---|---|---|---|--:|--:|--:|--:|--:|--:|--:|'
foreach ($c in $conv) {
    $skill = if ($c.skill) { $c.skill } else { '_(no skill)_' }
    $issue = if ($c.issue_key) { $c.issue_key } else { '-' }
    # A record with no measured metrics (skill_turns null: stub / unexpected /
    # no-skill) is listed for coverage but has no numbers — render its metric
    # cells as em-dashes and surface why, so a zero never reads as a real zero.
    $analyzedRow = ($null -ne $c.skill_turns)
    if ($analyzedRow) {
        $models = Join-List $c.models
        $t = $c.tokens
        W ("| ``{0}`` | {1} | {2} | {3} | {4} | {5} | {6} | {7} | {8} | {9} | {10} | {11} |" -f `
            $c.uuid, $c.provenance, $skill, $issue, $models, `
            (Num $t.in), (Num $t.out), (Num $t.cache_read), (Num $t.cache_write), (Num $t.total), `
            (Num $c.tool_calls), (Sec $c.wall_clock_s))
    } else {
        $why = "_not analyzed: $($c.key_status)_"
        W ("| ``{0}`` | {1} | {2} | {3} | {4} | — | — | — | — | — | — | — |" -f `
            $c.uuid, $c.provenance, $skill, $issue, $why)
    }
}
W ''

# ---- per-conversation performance table -------------------------------------
W '## Per-conversation — performance'
W ''
W '| conversation | skill | skill turns | sidechain turns | tool calls | tool errors | elapsed (s) | first activity | last activity |'
W '|---|---|--:|--:|--:|--:|--:|---|---|'
foreach ($c in $conv) {
    $skill = if ($c.skill) { $c.skill } else { '_(no skill)_' }
    if ($null -ne $c.skill_turns) {
        W ("| ``{0}`` | {1} | {2} | {3} | {4} | {5} | {6} | {7} | {8} |" -f `
            $c.uuid, $skill, (Num $c.skill_turns), (Num $c.sidechain_turns), `
            (Num $c.tool_calls), (Num $c.tool_errors), (Sec $c.wall_clock_s), `
            (Ts $c.first_ts), (Ts $c.last_ts))
    } else {
        W ("| ``{0}`` | {1} | — | — | — | — | — | — | — |" -f $c.uuid, $skill)
    }
}
W ''

# ---- tokens by skill --------------------------------------------------------
if ($null -ne $agg.by_skill -and @($agg.by_skill).Count -gt 0) {
    W '## Tokens by skill'
    W ''
    W '| skill | conversations | in | out | cache-read | cache-write | total |'
    W '|---|--:|--:|--:|--:|--:|--:|'
    foreach ($s in @($agg.by_skill)) {
        $t = $s.tokens
        W ("| {0} | {1} | {2} | {3} | {4} | {5} | {6} |" -f `
            $s.skill, (Num $s.conversations), (Num $t.in), (Num $t.out), `
            (Num $t.cache_read), (Num $t.cache_write), (Num $t.total))
    }
    W ''
}

# ---- tokens by provenance ---------------------------------------------------
if ($null -ne $agg.by_provenance -and @($agg.by_provenance).Count -gt 0) {
    W '## Tokens by provenance'
    W ''
    W '| provenance | conversations | in | out | cache-read | cache-write | total |'
    W '|---|--:|--:|--:|--:|--:|--:|'
    foreach ($p in @($agg.by_provenance)) {
        $t = $p.tokens
        W ("| {0} | {1} | {2} | {3} | {4} | {5} | {6} |" -f `
            $p.provenance, (Num $p.conversations), (Num $t.in), (Num $t.out), `
            (Num $t.cache_read), (Num $t.cache_write), (Num $t.total))
    }
    W ''
}

# ---- feature totals ---------------------------------------------------------
W '## Feature totals'
W ''
W '| token bucket | tokens |'
W '|---|--:|'
W "| input | $(Num $agg.tokens.in) |"
W "| output | $(Num $agg.tokens.out) |"
W "| cache read | $(Num $agg.tokens.cache_read) |"
W "| cache write | $(Num $agg.tokens.cache_write) |"
W "| **grand total** | **$(Num $agg.tokens.total)** |"
W ''
W "Models across the feature: **$(Join-List $agg.models)**"
W ''

# ---- activity timeframe -----------------------------------------------------
if ($agg.timeframe -and ($agg.timeframe.first_ts -or $agg.timeframe.last_ts)) {
    W '## Activity timeframe'
    W ''
    W '| metric | value |'
    W '|---|---|'
    W "| First activity | $(Ts $agg.timeframe.first_ts) |"
    W "| Last activity | $(Ts $agg.timeframe.last_ts) |"
    W "| Span (first → last) | $(Dur $agg.timeframe.span_s) |"
    W ''
    W "_Span is wall-clock from the earliest to the latest measured turn across the feature — it includes idle gaps between sessions and human wait time, so it is not compute time and does not equal the sum of per-conversation elapsed._"
    W ''
}

# ---- emit -------------------------------------------------------------------
# Emit on PowerShell's success stream (not [Console]::Out.Write), so `> file.md`
# captures the markdown whether this runs as its own process (pwsh -File …) or as
# a stage inside an existing session (… | .\feature_report.ps1). A direct console
# write bypasses the success stream, so in the pipeline-stage form `>` would
# redirect nothing and the markdown would land on the console with an empty file.
# One joined string keeps the LF line breaks intact (matches collect_feature,
# which emits its JSON the same way via ConvertTo-Json).
Write-Output ($out -join $nl)
exit 0
