#!/usr/bin/env python3
"""Generate the linked "setup tree" of a docs section from the docs tree itself.

The tree is the sidebar drawn as text: the same labels (`sidebar_label`, or a
category's `label`) in the same order (`sidebar_position` / `position`) that
Docusaurus's autogenerated sidebar uses, so it cannot drift from what a reader
sees on the left. Every node is a link.

It is written into any Markdown file carrying a marker pair:

    <!-- doc-tree: STEP-BY-STEP-INSTALLATION -->
    ...generated, do not edit by hand...
    <!-- /doc-tree -->

The argument is a directory under docs/. Link form follows AGENTS.md's URL
scheme: a target file under docs/ gets relative .md/.mdx links (versioning-safe);
a generated-index category, which has no backing file, gets its absolute site
URL; a file outside docs/ (the site front page) gets `/docs/<slug>` routes.
Only .md files are scanned — an HTML comment is a syntax error in .mdx.

    python3 scripts/gen-doc-tree.py                 # rewrite every marked region
    python3 scripts/gen-doc-tree.py --check         # exit 1 if any region is stale
    python3 scripts/gen-doc-tree.py --print DIR     # plain-text tree to stdout

Re-run it after adding, moving, renaming or re-ordering a page in a tree that is
drawn somewhere; `--check` names the stale file.
"""

from __future__ import annotations

import json
import os
import posixpath
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = "docs"
SCAN = [DOCS, "website/src/pages"]
SITE = json.load(open(os.path.join(REPO, "scripts", "docs-url-map.json"), encoding="utf-8"))["site_docs_base"]

MARKER = re.compile(
    r"(<!-- doc-tree: (?P<root>[^ ]+) -->\n)(?P<body>.*?)(<!-- /doc-tree -->)", re.S
)
# A literal no-break space, not `&nbsp;`: `cedit md canonicalize` decodes the
# entity, so emitting it would leave every generated region non-canonical.
NBSP = "\u00a0"


def front_matter(path: str) -> dict:
    text = open(path, encoding="utf-8").read()
    meta: dict = {}
    m = re.match(r"---\n(.*?)\n---\n", text, re.S)
    if m:
        for line in m.group(1).splitlines():
            k, sep, v = line.partition(":")
            if sep and not line.startswith((" ", "#")):
                meta[k.strip()] = v.strip().strip("\"'")
    h1 = re.search(r"^# (.+)$", text, re.M)
    meta.setdefault("h1", h1.group(1).strip() if h1 else None)
    return meta


def position(value) -> float | None:
    return None if value in (None, "") else float(value)


class Node:
    def __init__(self, label: str, file: str | None, slug: str, pos: float | None, name: str):
        self.label, self.file, self.slug, self.pos, self.name = label, file, slug, pos, name
        self.children: list[Node] = []


def doc_node(path: str) -> Node:
    meta = front_matter(path)
    slug = meta.get("slug")
    if not slug:
        sys.exit(f"gen-doc-tree: {os.path.relpath(path, REPO)} has no slug: front matter")
    label = meta.get("sidebar_label") or meta.get("title") or meta.get("h1") or os.path.basename(path)
    return Node(label, path, slug, position(meta.get("sidebar_position")), os.path.basename(path))


def category_node(directory: str) -> Node:
    cat_file = os.path.join(directory, "_category_.json")
    cat = json.load(open(cat_file, encoding="utf-8")) if os.path.exists(cat_file) else {}
    link = cat.get("link") or {}
    linked_doc = None
    if link.get("type") == "doc":
        stem = os.path.join(REPO, DOCS, link["id"])
        linked_doc = next((stem + ext for ext in (".md", ".mdx") if os.path.exists(stem + ext)), None)
        if not linked_doc:
            sys.exit(f"gen-doc-tree: {os.path.relpath(cat_file, REPO)} links to missing doc {link['id']}")
        node = doc_node(linked_doc)
        node.label = cat.get("label") or node.label
    elif link.get("type") == "generated-index":
        node = Node(cat.get("label") or os.path.basename(directory), None, link["slug"], None, "")
    else:
        sys.exit(f"gen-doc-tree: {os.path.relpath(directory, REPO)} has no linkable category page")
    node.pos, node.name = position(cat.get("position")), os.path.basename(directory)

    items = []
    for entry in sorted(os.listdir(directory)):
        full = os.path.join(directory, entry)
        if entry.startswith(("_", ".")) or full == linked_doc:
            continue
        if os.path.isdir(full):
            items.append(category_node(full))
        elif entry.endswith((".md", ".mdx")):
            items.append(doc_node(full))
    # Docusaurus's autogenerated order: positioned items first, by position;
    # the rest after them, in filename order (the sort above, kept stable).
    node.children = sorted(items, key=lambda n: (n.pos is None, n.pos or 0))
    return node


def walk(node: Node, prefix: str = "", last: bool = True, top: bool = True):
    """Yield (indent, branch, node) per line, box-drawing like `tree`."""
    yield ("", "", node) if top else (prefix, "└── " if last else "├── ", node)
    child_prefix = "" if top else prefix + ("    " if last else "│   ")
    for i, child in enumerate(node.children):
        yield from walk(child, child_prefix, i == len(node.children) - 1, False)


def href(node: Node, target: str) -> str:
    target_dir = os.path.dirname(target)
    in_docs = os.path.relpath(target, os.path.join(REPO, DOCS)).split(os.sep)[0] != ".."
    if not in_docs:
        return "/docs" + node.slug
    if node.file is None:
        return SITE + node.slug
    rel = posixpath.relpath(node.file.replace(os.sep, "/"), target_dir.replace(os.sep, "/"))
    return rel if rel.startswith("../") else "./" + rel


def render(root: Node, target: str) -> str:
    lines = []
    for indent, branch, node in walk(root):
        label = re.sub(r"([\[\]\\*_`<])", r"\\\1", node.label)
        lead = (indent + branch).replace(" ", NBSP)
        lines.append(f"{lead}[{label}]({href(node, target)})")
    # `\` is a CommonMark hard break; a no-break space survives both whitespace
    # collapsing and paragraph-continuation stripping, so the columns stay aligned.
    body = "\\\n".join(lines)
    return f'\n<div class="doc-tree">\n\n{body}\n\n</div>\n'


def plain(root: Node) -> str:
    return "\n".join(indent + branch + node.label for indent, branch, node in walk(root)) + "\n"


def tree_for(rel_root: str) -> Node:
    directory = os.path.join(REPO, DOCS, rel_root)
    if not os.path.isdir(directory):
        sys.exit(f"gen-doc-tree: no such docs directory: {rel_root}")
    return category_node(directory)


def targets():
    for base in SCAN:
        for dirpath, _, files in os.walk(os.path.join(REPO, base)):
            for f in sorted(files):
                if f.endswith(".md"):
                    path = os.path.join(dirpath, f)
                    if "<!-- doc-tree: " in open(path, encoding="utf-8").read():
                        yield path


def main(argv: list[str]) -> int:
    if argv[:1] == ["--print"] and len(argv) == 2:
        sys.stdout.write(plain(tree_for(argv[1])))
        return 0
    check = argv == ["--check"]
    if argv and not check:
        sys.exit(__doc__)
    stale = 0
    for path in targets():
        text = open(path, encoding="utf-8").read()
        new = MARKER.sub(lambda m: m.group(1) + render(tree_for(m.group("root")), path) + m.group(4), text)
        if new != text:
            stale += 1
            rel = os.path.relpath(path, REPO)
            if check:
                print(f"stale doc tree: {rel}")
            else:
                open(path, "w", encoding="utf-8").write(new)
                print(f"updated: {rel}")
    if check and stale:
        print("run: python3 scripts/gen-doc-tree.py")
    return 1 if check and stale else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
