// @ts-check
// Hand-written rather than generated by create-docusaurus: the scaffolder ships a
// tutorial, a blog and demo pages that all have to be deleted again.
//
// Three settings below are a contract, not a preference:
//   * url + baseUrl + docs.routeBasePath must keep producing
//     https://kantorv.github.io/jira-sdlc-tools/docs — that string is
//     scripts/docs-url-map.json's `site_docs_base`, and JST-287 baked URLs built
//     from it into plugin files that ship to users' plugin caches. Change any of
//     the three and every one of those links 404s for anyone who installed
//     rather than cloned.
//   * markdown.format and both broken-link hooks — see the comments on each.

import fs from 'node:fs';

import {themes as prismThemes} from 'prism-react-renderer';

// `docusaurus docs:version` writes versions.json newest-first and commits it, so
// releasedVersions[0] is always the current release — that's what lets the banner
// override below need no edit when a version is cut. Read rather than imported:
// import attributes (`with {type: 'json'}`) need Node >= 20.10 and package.json
// declares >= 20.0. The file does not exist before the first cut, so a missing
// one means "nothing released yet", not a build failure.
const versionsFile = new URL('./versions.json', import.meta.url);
const releasedVersions = fs.existsSync(versionsFile)
  ? JSON.parse(fs.readFileSync(versionsFile, 'utf8'))
  : [];
const latestRelease = releasedVersions[0];

// A slug that has shipped can never 404 — some of them are baked into plugin
// caches nobody can correct retroactively (AGENTS.md -> "The published docs URL
// scheme"). When a page moves or is split, its old slug moves to `redirects` in
// docs-url-map.json and is served from here instead. Read rather than
// hand-listed: a second copy of the list is how the redirect and the map drift.
// Only `current` is redirected — a versioned snapshot still carries the page at
// its own /docs/<X.Y.Z>/… route and must keep doing so.
const urlMap = JSON.parse(
  fs.readFileSync(new URL('../scripts/docs-url-map.json', import.meta.url), 'utf8'),
);
const docsRedirects = (urlMap.redirects ?? []).map(({slug, to}) => ({
  from: `/docs${slug}`,
  to: `/docs${to}`,
}));

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'jira-sdlc-tools',
  tagline: 'Plan, implement and review Jira issues with Claude Code skills',
  favicon: 'img/favicon.svg',

  url: 'https://kantorv.github.io',
  baseUrl: '/jira-sdlc-tools/',
  organizationName: 'kantorv',
  projectName: 'jira-sdlc-tools',

  // A missed reference is otherwise a silent 404 on a published page, found only
  // when a reader reports it — no test in this repo can see a broken doc link.
  // These two are what catch it, and they only catch it while set to 'throw'.
  onBrokenLinks: 'throw',
  onBrokenAnchors: 'warn',

  markdown: {
    // Docusaurus 3 parses .md as MDX, which makes `<` and `{` JSX syntax. This
    // corpus is placeholder-heavy (<KEY>, <DEFAULT_BASE_BRANCH>, <OWNER>, …), so
    // MDX would fail the build on ~19 files with errors that never mention angle
    // brackets. 'detect' parses .md as CommonMark and .mdx as MDX — which is why
    // no doc has to be edited to escape a placeholder. Want JSX in a page? Name
    // it .mdx.
    format: 'detect',
    mermaid: true,
    hooks: {
      // Lives under markdown.hooks since 3.x — the old top-level position still
      // works but emits a deprecation warning and disappears in v4.
      onBrokenMarkdownLinks: 'throw',
      // onBrokenMarkdownImages is deliberately left at its default ('throw').
      // Images are resolved by webpack, not the link checker, so neither hook
      // above covers them. Downgrading it to 'warn' to clear a failure just
      // ships a visibly broken page.
    },
  },

  themes: ['@docusaurus/theme-mermaid'],

  plugins: [
    ['@docusaurus/plugin-client-redirects', {redirects: docsRedirects}],
  ],

  i18n: {defaultLocale: 'en', locales: ['en']},

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          // The docs live at the repo root, where contributors and GitHub's own
          // renderer expect them. The site reads them; it does not own them, and
          // there is no copy step to keep in sync.
          path: '../docs',
          routeBasePath: 'docs',
          sidebarPath: './sidebars.js',
          editUrl: 'https://github.com/kantorv/jira-sdlc-tools/tree/main/',
          // Reads git history: needs fetch-depth: 0 in CI (JST-289). On a shallow
          // clone it degrades to "cannot infer the update date" warnings.
          showLastUpdateTime: true,
          // JST-294: `current` — i.e. ../docs, the unreleased working docs — is
          // the version served at the bare /docs/… route; released snapshots
          // move to /docs/<X.Y.Z>/…. This deliberately reverses Docusaurus's
          // default (newest *snapshot* at /docs/…, current at /docs/next/…),
          // because the URLs JST-287 baked into shipped plugin caches can never
          // be corrected retroactively: pointing them at current means a doc fix
          // reaches installed users on merge instead of at the next release cut.
          // Note this removes /docs/next/… entirely — it is the same route as
          // /docs/… now. routeBasePath, url and baseUrl are untouched, so
          // `site_docs_base` still resolves.
          lastVersion: 'current',
          versions: {
            // Without this the label is just "Next", which reads like a
            // release name; at the bare /docs/… route a visitor has no other
            // signal that these docs are ahead of every published version.
            current: {label: 'Next (unreleased)'},
            // Docusaurus banners every version that sorts after the last one as
            // "no longer actively maintained" — with current as the last, that
            // includes the newest snapshot, which is the *shipped* release and
            // is exactly where the dropdown sends readers. Suppress it there
            // only: 0.8.3 and older keep the banner, which is true of them.
            ...(latestRelease ? {[latestRelease]: {banner: 'none'}} : {}),
          },
        },
        blog: false,
        theme: {customCss: './src/css/custom.css'},
      }),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      colorMode: {defaultMode: 'light', respectPrefersColorScheme: true},
      // The default mermaid theme is not legible in dark mode — these two are
      // picked per colour mode so diagrams stay readable in both.
      mermaid: {theme: {light: 'neutral', dark: 'dark'}},
      navbar: {
        title: 'jira-sdlc-tools',
        items: [
          {
            type: 'docSidebar',
            sidebarId: 'docsSidebar',
            position: 'left',
            label: 'Docs',
          },
          // Every released snapshot is published, but until JST-294 nothing on
          // the site linked to one — a reader could only reach /docs/0.8.3/…
          // by typing it. This is that missing affordance; it needs no
          // maintenance as versions are cut, since it reads versions.json.
          {
            type: 'docsVersionDropdown',
            position: 'right',
          },
          {
            href: 'https://github.com/kantorv/jira-sdlc-tools',
            label: 'GitHub',
            position: 'right',
          },
        ],
      },
      footer: {
        style: 'dark',
        links: [
          {
            title: 'Docs',
            items: [
              {label: 'Installation', to: '/docs/installation'},
              // Was 'Step by step' -> /docs/step-by-step until JST-296 folded
              // that page into Installation; the two labels would now point at
              // one page. /docs/step-by-step still resolves, as a redirect.
              {label: 'Full setup checklist', to: '/docs/full-setup-checklist'},
              {label: 'Task lifecycle', to: '/docs/task-lifecycle'},
            ],
          },
          {
            title: 'Repository',
            items: [
              {
                label: 'GitHub',
                href: 'https://github.com/kantorv/jira-sdlc-tools',
              },
              {
                label: 'Releases',
                href: 'https://github.com/kantorv/jira-sdlc-tools/releases',
              },
            ],
          },
        ],
        copyright: `Copyright © ${new Date().getFullYear()} kantorv. Built with Docusaurus.`,
      },
      prism: {
        theme: prismThemes.github,
        darkTheme: prismThemes.dracula,
        additionalLanguages: ['bash', 'json', 'powershell', 'diff', 'yaml'],
      },
    }),
};

export default config;
