// @ts-check
// Hand-written rather than generated by create-docusaurus: the scaffolder ships a
// tutorial, a blog and demo pages that all have to be deleted again.
//
// Three settings below are a contract, not a preference:
//   * url + baseUrl + docs.routeBasePath must keep producing
//     https://kantorv.github.io/jira-sdlc-tools/docs — that string is
//     scripts/docs-url-map.json's `site_docs_base`, and JST-287 baked URLs built
//     from it into plugin files that ship to users' plugin caches. Change any of
//     the three and every one of those links 404s for anyone who installed
//     rather than cloned.
//   * markdown.format and both broken-link hooks — see the comments on each.

import {themes as prismThemes} from 'prism-react-renderer';

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'jira-sdlc-tools',
  tagline: 'Plan, implement and review Jira issues with Claude Code skills',
  favicon: 'img/favicon.svg',

  url: 'https://kantorv.github.io',
  baseUrl: '/jira-sdlc-tools/',
  organizationName: 'kantorv',
  projectName: 'jira-sdlc-tools',

  // A missed reference is otherwise a silent 404 on a published page, found only
  // when a reader reports it — no test in this repo can see a broken doc link.
  // These two are what catch it, and they only catch it while set to 'throw'.
  onBrokenLinks: 'throw',
  onBrokenAnchors: 'warn',

  markdown: {
    // Docusaurus 3 parses .md as MDX, which makes `<` and `{` JSX syntax. This
    // corpus is placeholder-heavy (<KEY>, <DEFAULT_BASE_BRANCH>, <OWNER>, …), so
    // MDX would fail the build on ~19 files with errors that never mention angle
    // brackets. 'detect' parses .md as CommonMark and .mdx as MDX — which is why
    // no doc has to be edited to escape a placeholder. Want JSX in a page? Name
    // it .mdx.
    format: 'detect',
    mermaid: true,
    hooks: {
      // Lives under markdown.hooks since 3.x — the old top-level position still
      // works but emits a deprecation warning and disappears in v4.
      onBrokenMarkdownLinks: 'throw',
      // onBrokenMarkdownImages is deliberately left at its default ('throw').
      // Images are resolved by webpack, not the link checker, so neither hook
      // above covers them. Downgrading it to 'warn' to clear a failure just
      // ships a visibly broken page.
    },
  },

  themes: ['@docusaurus/theme-mermaid'],

  i18n: {defaultLocale: 'en', locales: ['en']},

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          // The docs live at the repo root, where contributors and GitHub's own
          // renderer expect them. The site reads them; it does not own them, and
          // there is no copy step to keep in sync.
          path: '../docs',
          routeBasePath: 'docs',
          sidebarPath: './sidebars.js',
          editUrl: 'https://github.com/kantorv/jira-sdlc-tools/tree/main/',
          // Reads git history: needs fetch-depth: 0 in CI (JST-289). On a shallow
          // clone it degrades to "cannot infer the update date" warnings.
          showLastUpdateTime: true,
        },
        blog: false,
        theme: {customCss: './src/css/custom.css'},
      }),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      colorMode: {defaultMode: 'light', respectPrefersColorScheme: true},
      // The default mermaid theme is not legible in dark mode — these two are
      // picked per colour mode so diagrams stay readable in both.
      mermaid: {theme: {light: 'neutral', dark: 'dark'}},
      navbar: {
        title: 'jira-sdlc-tools',
        items: [
          {
            type: 'docSidebar',
            sidebarId: 'docsSidebar',
            position: 'left',
            label: 'Docs',
          },
          {
            href: 'https://github.com/kantorv/jira-sdlc-tools',
            label: 'GitHub',
            position: 'right',
          },
        ],
      },
      footer: {
        style: 'dark',
        links: [
          {
            title: 'Docs',
            items: [
              {label: 'Installation', to: '/docs/installation'},
              {label: 'Step by step', to: '/docs/step-by-step'},
              {label: 'Task lifecycle', to: '/docs/task-lifecycle'},
            ],
          },
          {
            title: 'Repository',
            items: [
              {
                label: 'GitHub',
                href: 'https://github.com/kantorv/jira-sdlc-tools',
              },
              {
                label: 'Releases',
                href: 'https://github.com/kantorv/jira-sdlc-tools/releases',
              },
            ],
          },
        ],
        copyright: `Copyright © ${new Date().getFullYear()} kantorv. Built with Docusaurus.`,
      },
      prism: {
        theme: prismThemes.github,
        darkTheme: prismThemes.dracula,
        additionalLanguages: ['bash', 'json', 'powershell', 'diff', 'yaml'],
      },
    }),
};

export default config;
