// Autogenerated from the docs tree, not hand-listed. A hand-written list is a
// second copy of an ordering decision that also lives in the files, and it goes
// stale the first time someone adds a page and updates only one of the two. At
// 55 files that is a certainty, not a risk.
//
// Autogenerated is not alphabetised: order comes from `sidebar_position` in each
// page's front matter and `position` in each `_category_.json` (both supplied by
// JST-287). A page added with no position lands at the end rather than
// displacing anything.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
